## QA / conceptual basics for NumPy

NumPy is an open-source, high-performing library that allows complex mathematical and scientific computational capabilities. It makes use of Python language which is a high-level, easy-to-learn, general-purpose programming language. NumPy supports the operations on arrays of homogenous data so that it can take advantage of C optimized backend code (C requiring set, homogenous data types). This makes Python act as a really advanced programming language that manipulates numerical data. It increases the functionality and operability of NumPy. It supports the following:

-Powerful functions for performing complex mathematical operations on multi-dimensional matrices and arrays. The operations on ndarrays of NumPy are approximately up to 50% faster when compared to operations on native lists using loops. This efficiency is very much useful 

-when the arrays have millions of elements.

-Provides indexing syntax to access portions of data easily in a large array.

-Provides built-in functions which help to easily perform operations related to linear algebra and statistics.

-It takes only a few lines of code to achieve complex computations using NumPy.

NumPy compared to Lists

-Python lists support storing heterogeneous data types whereas NumPy arrays can store datatypes of one nature itself. NumPy provides extra functional capabilities that make operating on its arrays easier which makes NumPy array advantageous in comparison to Python lists as those functions cannot be operated on heterogeneous data.

-NumPy arrays are treated as objects which results in minimal memory usage. Since Python keeps track of objects by creating or deleting them based on the requirements, NumPy objects are also treated the same way. This results in lesser memory wastage.

-NumPy arrays support multi-dimensional arrays.

-NumPy provides various powerful and efficient functions for complex computations on the arrays.

-NumPy also provides various range of functions for BitWise Operations, String Operations, Linear Algebraic operations, Arithmetic operations etc. These are not provided on Python’s default lists.

What are ndarrays in NumPy?

ndarray object is the core of the NumPy package. It consists of n-dimensional arrays storing elements of the same data types and also has many operations that are done in compiled code for optimised performance. These arrays have fixed sizes defined at the time of creation. Following are some of the properties of ndarrays:

-When the size of ndarrays is changed, it results in a new array and the original array is deleted.

-The ndarrays are bound to store homogeneous data.

-They provide functions to perform advanced mathematical operations in an efficient manner.

What are ways of creating 1D, 2D and 3D arrays in NumPy?

# 1D
```
arr = [1,2,3,4]
np_arr = np.array(arr)
```

# 2D

```
arr = [[1,2,3,4],[4,5,6,7]]
np_arr = np.array(arr)
```

Datatypes

NumPy supports the following datatypes:

    i - integer
    S - string
    b - boolean
    f - float
    u - unsigned integer
    c - complex float
    m - timedelta
    M - datetime
    O - object
    U - unicode string
    V - fixed memory chunk for types such as void
    We can make use of the dtype property that returns the type of the elements stored in the NumPy array. Let us consider the below code snippet. We create some sample arrays and we see what the data types of these arrays are.

```
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array(['I', 'love', 'Interviewbit'])    # Stored as Unicode characters with length of characters ranging from 1 to 12
arr3 = np.array([1, 2, 3, 4], dtype='S')        # Creating numpy array of defined type string
```

Types would be : int64, <U12, |S1 (int, unicode str, string)

How do you reverse a NumPy Array?

reverse_arr = arr[::-1] OR for a 1D array, np.flipud(arr)

How is np.mean() different from np.average()?

Mean is the arithmetic mean, but for average youi can provide a weighting vector and calculate a weighted average

How do you count the frequency of a given positive value appearing in the NumPy array?

np.bincount(arr)

Explain ravel and flatten and how they are different?

Both produce 1D versions of an ndarray. However, flatten returns a copy and ravel returns a view, meaning ravel is faster but you may alter the original array

How to find indices in an array based on a T/F condition?

np.nonzero(A) finds the indices of an array where the elems of A are not zero. If we pass np.nonzero(A > 1), A > 1 on its own calculates a T / F matrix where each elem of A
is T or F. In np T is represented as 1 and F as 0, so adding nonzero() on top will find all the True indices

How do you check for an empty array / zero elems array?

arr.size will return zero. Note len() off the same arr would return 1

How to update, insert, delete rows or columns in numpy?

np.delete, np.insert for the obvious applications, probably indexing to update

Explain how is arr[:,0] different from arr[:,[0]]?

arr[:,0] Returns 0th index elements of all rows. In other words, return the first column elements while arr[:,[0]] returns the elements of the first column by adding extra dimension to it.

# option 1
arr = np.array([[1,2,3,4],[5,6,7,8]])
new_arr =arr[:,[0]]
print(new_arr)

Output:

 [1 5]


# option 2

arr = np.array([[1,2,3,4],[5,6,7,8]])
new_arr =arr[:,[0]]
print(new_arr)

Output:

[[1]
[5]]

How to multiply two arrays / matrices ?

np.dot() for the dot product

How to concatenate two arrays?

np.concatenate() and you can specify the axis

How to convert from pandas df to np array?

df.to_numpy()

What is vectorization?

You can vectorize a function to be applied elementwise to one or multiple matrices.

def add(arr1, arr2):
    return (arr1 + arr2)

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

#vectorize add method
vectorized_add = np.vectorize(add)

#call vectorized method
result = vectorized_add(arr1, arr2)

result output is [5,7,9]

How to find local maxima using np?

# look for where the previous and post values are less than the current value
maxima_peaks_positions = np.where((arr[1:-1] > arr[0:-2]) * (arr[1:-1] > arr[2:]))[0] + 1

How is vectorization related to broadcasting?

Vectorization involves delegating NumPy operations internally to optimized C language functions to result in faster Python code. Whereas Broadcasting refers to the methods that allow NumPy to perform array-related arithmetic operations. The size or shape of the arrays does not matter in this case. Broadcasting solves the problem of mismatched shaped arrays by replicating the smaller array along the larger array to ensure both arrays are having compatible shapes for NumPy operations. Performing Broadcasting before Vectorization helps to vectorize operations which support arrays of different dimensions.

What happens when using np.split()?

split array into equal sections defined by n, if not possible return error

What about np.arrays_split?

Same as above, but it doesn't return an error if it can't produce equal length arrays, just has a leftover Length % N

How to find a moving average in NumPy?

def calculate_moving_average(arr, w):
    return np.convolve(arr, np.ones(w),'valid')/w

where w is the window length

## Coding examples

In [1]:
import numpy as np

In [2]:
# case conversion

arr = np.array(['i', 'love', 'NumPy', 'AND', 'interviewbit'], dtype=str)

upper_case_arr = np.char.upper(arr)
lower_case_arr = np.char.lower(arr)
capitalize_case_arr = np.char.capitalize(arr)
titlecase_arr = np.char.title(arr)
swapcase_arr = np.char.swapcase(arr)

print("Upper Conversion: ", upper_case_arr)
print("Lower Conversion: ", lower_case_arr)
print("Capitalize First Letter Conversion: ", capitalize_case_arr)
print("Titlecase Conversion: ", titlecase_arr)
print("Swapcase Conversion: ", swapcase_arr)

Upper Conversion:  ['I' 'LOVE' 'NUMPY' 'AND' 'INTERVIEWBIT']
Lower Conversion:  ['i' 'love' 'numpy' 'and' 'interviewbit']
Capitalize First Letter Conversion:  ['I' 'Love' 'Numpy' 'And' 'Interviewbit']
Titlecase Conversion:  ['I' 'Love' 'Numpy' 'And' 'Interviewbit']
Swapcase Conversion:  ['I' 'LOVE' 'nUMpY' 'and' 'INTERVIEWBIT']


In [3]:
# Write a program to transform elements of a given string to a numeric string of 10 digits by making all the elements
# of a given string to a numeric string of 8 digits with zeros on the left.

arr = np.array(['22', '9', '1234', '567', '89102'], dtype=str)

zeroes_filled_arr = np.char.zfill(arr, 8)
print("Transformed array: ")
print(zeroes_filled_arr)

Transformed array: 
['00000022' '00000009' '00001234' '00000567' '00089102']


In [4]:
# Write a program for inserting space between characters of all elements in a NumPy array.

arr = np.array(['i', 'love', 'NumPy', 'AND', 'interviewbit'], dtype=str)

transformed_arr = np.char.join(" ", arr)

print("Transformed Array: ")
print(transformed_arr)

Transformed Array: 
['i' 'l o v e' 'N u m P y' 'A N D' 'i n t e r v i e w b i t']


In [5]:
# Write a program to repeat each of the elements in the array 5 times

arr = np.array(['i', 'love', 'NumPy', 'AND', 'interviewbit'], dtype=str)

transformed_array = np.char.multiply(arr, 5)
print("Transformed array:")
print(transformed_array)

Transformed array:
['iiiii' 'lovelovelovelovelove' 'NumPyNumPyNumPyNumPyNumPy'
 'ANDANDANDANDAND'
 'interviewbitinterviewbitinterviewbitinterviewbitinterviewbit']


In [6]:
# Write a program for creating an integer array with values belonging to the range 10 and 60

arr = np.arange(10, 60)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59]


In [7]:
# Write a program to add a border of zeros around the existing array

ones_arr = np.ones((4,4))

print("Transformed array:")
transformed_array = np.pad(ones_arr, pad_width=1, mode='constant', constant_values=0)
print(transformed_array)

Transformed array:
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [8]:
# Write a program for changing the dimension of a NumPy array

arr = np.array([1,2,3,4,5,6,7,8,9])
print("Original Shape: ", arr.shape)

# Change the shape/dimension of the array by changing .shape attr
# note that the number of elements between dimensions needs to stay constant
# there is another method as well .reshape(): np.reshape(arr,(m,n))


Original Shape:  (9,)
Transformed Matrix :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transformed Shape:  (3, 3)


In [9]:
a = np.array([(1,2,50)])

print(a.itemsize)

4


In [10]:
print(a)

[[ 1  2 50]]
